alias tmux='tmux -2'
alias ta='tmux attach -t'
alias tnew='tmux new -s'
alias tls='tmux ls'
alias tkill='tmux kill-session -t'
alias config='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias scrfix='xrandr --output eDP1 --mode 1920x1080 --scale 1x1 --output HDMI2 --off'
alias junit='java -cp /home/vincent/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/vincent/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:. org.junit.runner.JUnitCore'
alias junitc='javac -cp /home/vincent/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/vincent/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:. '
