alias tmux='tmux -2'
alias ta='tmux attach -t'
alias tnew='tmux new -s'
alias tls='tmux ls'
alias tkill='tmux kill-session -t'
alias config='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias scrfix='xrandr --output eDP1 --mode 1920x1080 --scale 1x1 --output HDMI2 --off'
